//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNO
    {
        public ALUMNO()
        {
            this.MATRICULAs = new HashSet<MATRICULA>();
        }
    
        public Nullable<decimal> DNI_ALUMNO { get; set; }
        public decimal CODIGO_ALUMNO { get; set; }
        public string NOMBRES_ALUMNO { get; set; }
        public string APELLIDOS_ALUMNO { get; set; }
        public string ESTADO_ALUMNO { get; set; }
    
        public virtual ICollection<MATRICULA> MATRICULAs { get; set; }
    }
}
