//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CURSO
    {
        public CURSO()
        {
            this.VACANTEs = new HashSet<VACANTE>();
            this.MATRICULAs = new HashSet<MATRICULA>();
        }
    
        public decimal ID_CURSO { get; set; }
        public string DESCRIPCION_CURSO { get; set; }
        public Nullable<decimal> CANTIDADCREDITOS_CURSO { get; set; }
    
        public virtual ICollection<VACANTE> VACANTEs { get; set; }
        public virtual ICollection<MATRICULA> MATRICULAs { get; set; }
    }
}
