//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MatriculaEntities : DbContext
    {
        public MatriculaEntities()
            : base("name=MatriculaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALUMNO> ALUMNOes { get; set; }
        public DbSet<CURSO> CURSOes { get; set; }
        public DbSet<SECCION> SECCIONs { get; set; }
        public DbSet<TIPOMATRICULA> TIPOMATRICULAs { get; set; }
        public DbSet<VACANTE> VACANTEs { get; set; }
        public DbSet<MATRICULA> MATRICULAs { get; set; }
    
        public virtual int SP_CREATE_MATRICULA(Nullable<decimal> tIPO_MATRICULA_V, Nullable<decimal> cODIGO_ALUMNO_V, Nullable<decimal> iD_CURSO_V)
        {
            var tIPO_MATRICULA_VParameter = tIPO_MATRICULA_V.HasValue ?
                new ObjectParameter("TIPO_MATRICULA_V", tIPO_MATRICULA_V) :
                new ObjectParameter("TIPO_MATRICULA_V", typeof(decimal));
    
            var cODIGO_ALUMNO_VParameter = cODIGO_ALUMNO_V.HasValue ?
                new ObjectParameter("CODIGO_ALUMNO_V", cODIGO_ALUMNO_V) :
                new ObjectParameter("CODIGO_ALUMNO_V", typeof(decimal));
    
            var iD_CURSO_VParameter = iD_CURSO_V.HasValue ?
                new ObjectParameter("ID_CURSO_V", iD_CURSO_V) :
                new ObjectParameter("ID_CURSO_V", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_MATRICULA", tIPO_MATRICULA_VParameter, cODIGO_ALUMNO_VParameter, iD_CURSO_VParameter);
        }
    }
}
