//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATRICULA
    {
        public decimal ID_MATRICULA { get; set; }
        public Nullable<decimal> TIPO_MATRICULA { get; set; }
        public Nullable<System.DateTime> FECHA_MATRICULA { get; set; }
        public Nullable<System.DateTime> FECHAANULACION_MATRICULA { get; set; }
        public Nullable<decimal> CODIGO_ALUMNO { get; set; }
        public Nullable<decimal> ID_CURSO { get; set; }
    
        public virtual ALUMNO ALUMNO { get; set; }
        public virtual CURSO CURSO { get; set; }
        public virtual TIPOMATRICULA TIPOMATRICULA { get; set; }
    }
}
