//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECCION
    {
        public SECCION()
        {
            this.VACANTEs = new HashSet<VACANTE>();
        }
    
        public decimal ID_SECCION { get; set; }
        public string NOMBRE_SECCION { get; set; }
        public string ESTADO_SECCION { get; set; }
    
        public virtual ICollection<VACANTE> VACANTEs { get; set; }
    }
}
