//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACANTE
    {
        public decimal ID_VACANTE { get; set; }
        public Nullable<decimal> ID_SECCION { get; set; }
        public Nullable<decimal> ID_CURSO { get; set; }
        public Nullable<decimal> NUMERO_VACANTES { get; set; }
    
        public virtual CURSO CURSO { get; set; }
        public virtual SECCION SECCION { get; set; }
    }
}
